#############################################################
#                                                           #
# Copyright (c) 2022, University of California, Los Angeles #
#                                                           #
# Authors: Kenny J. Chen, Brett T. Lopez                    #
# Contact: kennyjchen@ucla.edu, btlopez@ucla.edu            #
#                                                           #
#############################################################

dlo:

  odomNode:
    debugVerbose: false
    initialPose:
      use: false
      position:
        x: 0.0
        y: 0.0
        z: 0.0
      orientation:
        w: 1.0
        x: 0.0
        y: 0.0
        z: 0.0

    preprocessing:
      cropBoxFilter:
        use: true
        size: 1.0
      voxelFilter:
        scan:
          use: true
          res: 0.25
        submap:
          use: false
          res: 0.25

    keyframe:
      threshD: 1.0
      threshR: 45.0

    submap:
      keyframe:
        knn: 10
        kcv: 10
        kcc: 10

    imu:
      calibTime: 3
      bufferSize: 2000
      extrinsicTrans: [0.0, 0.0, 0.0]
      # extrinsicRot: [-1, 0, 0,
      #                 0, 1, 0,
      #                 0, 0, -1]
      # extrinsicRPY: [0,  1, 0,
      #                -1, 0, 0,
      #                 0, 0, 1]
      extrinsicRot: [1, 0, 0,
                  0, 1, 0,
                  0, 0, 1]
      extrinsicRPY: [1, 0, 0,
                  0, 1, 0,
                  0, 0, 1]
    gicp:
      minNumPoints: 64
      s2m:
        kCorrespondences: 16
        maxCorrespondenceDistance: 0.5
        maxIterations: 32
        transformationEpsilon: 0.01
        euclideanFitnessEpsilon: 0.01
        ransac:
          iterations: 5
          outlierRejectionThresh: 1.0